// Mode Augments Module - builds Arena-borrowed and ARAM: Mayhem ("kiwi")
// augments from raw CommunityDragon game files.
//
// CommunityDragon's cdragon/arena/{lang}.json is generated by CDTB's
// arenadata.py, which only reads map30.bin. Since 26.19 Arena also pulls
// augments from Maps/ModeSpecificData/Augments (the Mayhem pool), and those
// never make it into that JSON. This module does the same transform as
// arenadata.py, but against the files those augments actually live in:
//
//   game/maps/modespecificdata/kiwi.bin.json   AugmentData + SpellObjects (numbers)
//   plugins/.../v1/augment-lists.json          which paths each mode uses (CHERRY / KIWI)
//   plugins/.../v1/cherry-augments.json        id / name / rarity / icon for every augment
//   game/{lang}/data/menu/{lang}/lol.stringtable.json   names + description text
//
// Every Arena entry resolves through the most dynamic source available:
//   1. AugmentData in PBE kiwi.bin (with Arena's DataValuesModeOverride), by
//      path, by hashed path, or by AugmentNameId ignoring an "ARAM_" prefix
//   2. the same lookup in latest (live) kiwi.bin — fetched only if something
//      is still unresolved and has no hard-coded fallback
//   3. cherry-augments.json metadata + stringtable text, with numbers from
//      js/data/arenaAugmentFallbacks.js (only the parts nothing else provides)
// Output objects match the en_us.json augment shape so the calculation engine
// and renderer treat them exactly like native Arena augments.

import { arenaAugmentFallbacks, cherryAugmentListSnapshot } from './data/arenaAugmentFallbacks.js';
import { xxh3_64 } from './xxh3.js';

const CDRAGON_BASE = 'https://raw.communitydragon.org/pbe/';
const GAME_DATA_BASE = CDRAGON_BASE + 'plugins/rcp-be-lol-game-data/global/default/v1/';
export const kiwiBinUrl = CDRAGON_BASE + 'game/maps/modespecificdata/kiwi.bin.json';
export const liveKiwiBinUrl = 'https://raw.communitydragon.org/latest/game/maps/modespecificdata/kiwi.bin.json';
export const augmentListsUrl = GAME_DATA_BASE + 'augment-lists.json';
export const cherryAugmentsUrl = GAME_DATA_BASE + 'cherry-augments.json';

export function stringtableUrl(language) {
    return `${CDRAGON_BASE}game/${language}/data/menu/${language}/lol.stringtable.json`;
}

// cherry-augments.json rarity enum → en_us.json numeric rarity.
const RARITY_BY_NAME = { kSilver: 0, kGold: 1, kPrismatic: 2, kEventChoice: 4 };

// Placeholders that are filled at render time without dataValues
// (runtime-only @f1@ values and the Q/W/E/R keybind mappings).
const RUNTIME_PLACEHOLDER = /^(f\d+(\.\d+)?|spell\d+KeyBind)$/;

const jsonCache = new Map();

function fetchJson(url) {
    if (!jsonCache.has(url)) {
        const promise = fetch(url).then((response) => {
            if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`);
            return response.json();
        });
        // Don't cache failures, so a later call can retry.
        promise.catch(() => jsonCache.delete(url));
        jsonCache.set(url, promise);
    }
    return jsonCache.get(url);
}

// Stringtable entries for a language (keys are lowercased). Shared with the
// arena item description loader so the ~30MB file is only downloaded once.
export async function getStringtable(language = 'en_us') {
    const data = await fetchJson(stringtableUrl(language));
    return data.entries || data;
}

// RST hash widths CDTB has used (38 bits for 15.02+, 39/40 for older files).
const STRING_HASH_MASKS = [38n, 39n, 40n].map((bits) => (1n << bits) - 1n);

function lookupString(strings, key) {
    if (!key) return undefined;
    const lowered = key.toLowerCase();
    if (strings[lowered] !== undefined) return strings[lowered];
    // Keys CommunityDragon can't name yet are printed as `{xxh3 hash}`.
    const hash = xxh3_64(lowered);
    if (hash === null) return undefined;
    for (const mask of STRING_HASH_MASKS) {
        const value = strings['{' + (hash & mask).toString(16).padStart(10, '0') + '}'];
        if (value !== undefined) return value;
    }
    return undefined;
}

// Inline `{{ Some_Key }}` references to other stringtable entries
// (e.g. Scavenger's tooltip embeds `{{Cherry_Scavenger_Summary}}`).
function resolveNestedStrings(text, strings, depth = 0) {
    if (!text || depth > 3) return text;
    return text.replace(/\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g, (match, key) => {
        const nested = lookupString(strings, key);
        return nested !== undefined ? resolveNestedStrings(nested, strings, depth + 1) : match;
    });
}

function localizedText(strings, key) {
    return resolveNestedStrings(lookupString(strings, key), strings);
}

// Same conversion CDTB applies (tools.convert_cdragon_path): lowercase, .tex/.dds → .png.
function toCdragonPath(path) {
    if (!path) return '';
    return path.toLowerCase().replace(/\.(tex|dds)$/, '.png');
}

// cherry-augments.json icons look like `/lol-game-data/assets/ASSETS/UX/...`;
// the same files live under game/assets/ux/... in CommunityDragon.
function clientIconToGamePath(path) {
    if (!path) return '';
    return path.replace(/^\/lol-game-data\/assets\//i, '').toLowerCase();
}

function normalizeApiName(name) {
    return (name || '').toLowerCase().replace(/^aram_/, '');
}

function readDataValueList(list, into) {
    for (const dv of list || []) {
        const name = dv.name ?? dv.mName;
        if (name === undefined) continue;
        into[name] = dv.values ?? dv.mValues ?? [0, 0, 0, 0, 0, 0, 0];
    }
    return into;
}

// Data value / calculation names CommunityDragon can't name are exported as
// `{fnv1a hash}`. For each @Name@ the text uses that's missing, copy the
// hashed entry under its real name so the calculation engine finds it.
function aliasHashedNames(text, values) {
    for (const [, name] of text.matchAll(/@([A-Za-z0-9_]+)(?:\*-?[\d.]+)?@/g)) {
        if (values[name] !== undefined) continue;
        const hashed = values[binPathHash(name)];
        if (hashed !== undefined) values[name] = hashed;
    }
}

// Build an en_us.json-shaped augment from a bin AugmentData entry. `mode`
// selects a DataValuesModeOverride block ('cherry' for Arena), so borrowed
// augments show Arena's numbers rather than Mayhem's.
function buildFromBin(augmentData, bin, strings, mode, dataSource) {
    const spellObject = bin[augmentData.RootSpell];
    const spell = spellObject && spellObject.mSpell;

    const dataValues = {};
    let calculations = {};
    if (spell) {
        readDataValueList(spell.DataValues || spell.mDataValues, dataValues);
        const override = mode && spell.DataValuesModeOverride && spell.DataValuesModeOverride[mode];
        if (override) readDataValueList(override.SpellDataValues, dataValues);
        // Copied because aliasHashedNames adds keys, and the bin is cached.
        calculations = { ...(spell.mSpellCalculations || {}) };
    }

    const desc = localizedText(strings, augmentData.DescriptionTra) ?? '';
    const tooltip = localizedText(strings, augmentData.AugmentTooltipTra) ?? '';
    aliasHashedNames(desc + tooltip, dataValues);
    aliasHashedNames(desc + tooltip, calculations);

    const iconSmall = toCdragonPath(augmentData.AugmentSmallIconPath);
    return {
        id: augmentData.AugmentPlatformId,
        apiName: augmentData.AugmentNameId,
        name: localizedText(strings, augmentData.NameTra) ?? augmentData.AugmentNameId,
        desc,
        tooltip,
        iconSmall,
        iconLarge: toCdragonPath(augmentData.AugmentLargeIconPath) || iconSmall,
        rarity: augmentData.rarity ?? 0,
        dataValues,
        calculations,
        dataSource
    };
}

// True when every @placeholder@ in `text` can be filled by the renderer.
function placeholdersResolvable(text, dataValues) {
    const tokens = text.match(/@([A-Za-z0-9_.]+)(\*-?[\d.]+)?@/g) || [];
    return tokens.every((token) => {
        const name = token.slice(1, -1).split('*')[0];
        return RUNTIME_PLACEHOLDER.test(name) || Object.prototype.hasOwnProperty.call(dataValues, name);
    });
}

function applyTextValues(text, textValues) {
    if (!textValues) return text;
    return text.replace(/@([A-Za-z0-9_]+)@/g, (match, name) =>
        Object.prototype.hasOwnProperty.call(textValues, name) ? textValues[name] : match);
}

function candidateTextKeys(apiName, fallback) {
    const base = normalizeApiName(apiName);
    const keys = [...(fallback?.descKeys || [])];
    for (const suffix of ['summary', 'description', 'tooltip']) {
        for (const prefix of ['cherry_', 'kiwi_', 'kiwi_aram_', 'kiwi_augment_', 'augment_', '']) {
            keys.push(`${prefix}${base}_${suffix}`);
        }
    }
    return [...new Set(keys)];
}

// Pick description text for an augment with no bin data. Prefers stringtable
// text whose numbers we can fill; then the hard-coded desc; then any
// stringtable text at all (unfilled numbers render as [Name]).
function pickFallbackText(apiName, fallback, strings, dataValues) {
    const texts = candidateTextKeys(apiName, fallback)
        .map((key) => localizedText(strings, key))
        .filter(Boolean)
        .map((text) => applyTextValues(text, fallback?.textValues));
    return texts.find((text) => placeholdersResolvable(text, dataValues))
        ?? fallback?.desc
        ?? texts[0]
        ?? '';
}

// `useTable` = false skips the hard-coded table, whose numbers are Arena's.
function buildFromFallback(apiName, clientMeta, strings, useTable = true) {
    const fallback = useTable ? arenaAugmentFallbacks[apiName] : undefined;
    if (!clientMeta && !fallback) return null;

    const dataValues = fallback?.dataValues ? structuredClone(fallback.dataValues) : {};
    const iconSmall = clientIconToGamePath(clientMeta?.augmentSmallIconPath);
    return {
        id: clientMeta?.id ?? fallback.id,
        apiName,
        name: clientMeta?.nameTRA || fallback?.name || apiName,
        desc: pickFallbackText(apiName, fallback, strings, dataValues),
        tooltip: '',
        iconSmall: iconSmall || fallback?.iconLarge || '',
        iconLarge: fallback?.iconLarge || iconSmall,
        rarity: clientMeta ? (RARITY_BY_NAME[clientMeta.rarity] ?? 0) : (fallback?.rarity ?? 0),
        dataValues,
        calculations: {},
        dataSource: fallback ? 'fallback' : 'client-metadata'
    };
}

async function settle(promise) {
    try {
        return await promise;
    } catch (error) {
        console.warn('[modeAugments]', error.message);
        return null;
    }
}

// Bin entry keys are FNV-1a hashes of the lowercased path. CommunityDragon
// prints the path when it knows the name and `{hash}` when it doesn't (common
// on PBE right after new augments ship), so look up both.
function binPathHash(path) {
    let hash = 0x811c9dc5;
    for (const byte of new TextEncoder().encode(path.toLowerCase())) {
        hash = Math.imul(hash ^ byte, 0x01000193) >>> 0;
    }
    return '{' + hash.toString(16).padStart(8, '0') + '}';
}

function indexBin(bin) {
    const byName = {};
    for (const entry of Object.values(bin || {})) {
        if (entry && entry.__type === 'AugmentData') byName[normalizeApiName(entry.AugmentNameId)] = entry;
    }
    const augmentAt = (key) => (bin[key] && bin[key].__type === 'AugmentData') ? bin[key] : undefined;
    return {
        bin: bin || {},
        size: Object.keys(byName).length,
        // `byNameToo` also accepts an AugmentData with the same AugmentNameId
        // at a different path (e.g. CHERRY's Quest_VoidImmolation is kiwi's
        // ARAM_Quest_VoidImmolation).
        find(path, byNameToo) {
            return augmentAt(path) ?? augmentAt(binPathHash(path))
                ?? (byNameToo ? byName[normalizeApiName(path.split('/').pop())] : undefined);
        }
    };
}

// Load borrowed Arena augments and the full ARAM: Mayhem list.
// Returns { arena: Augment[], aram: Augment[] | null, report }. `aram` is null
// when the kiwi bin or stringtable couldn't be loaded, so callers can fall back
// to their legacy icon-only list.
export async function loadModeAugments(language = 'en_us') {
    const [kiwiBin, augmentLists, cherryAugments, strings] = await Promise.all([
        settle(fetchJson(kiwiBinUrl)),
        settle(fetchJson(augmentListsUrl)),
        settle(fetchJson(cherryAugmentsUrl)),
        settle(getStringtable(language))
    ]);
    const stringsOrEmpty = strings || {};

    // Without the stringtable, bin entries would have no names or text.
    const kiwi = indexBin(strings ? kiwiBin : null);

    const clientMetaByName = {};
    for (const meta of cherryAugments || []) {
        clientMetaByName[meta.augmentNameId.toLowerCase()] = meta;
    }

    const modeList = (modeName) => (augmentLists || []).find((l) => l.modeName === modeName)?.augmentList;
    const cherryPaths = modeList('CHERRY') || cherryAugmentListSnapshot;
    const apiNameOf = (path) => path.split('/').pop();

    // PBE occasionally drops a definition live still has (e.g. Crit 'n Cast
    // in 16.21). Only pay for the second 12MB download when an Arena augment
    // would otherwise have no numbers at all.
    let liveKiwi = null;
    const needsLive = cherryPaths.some((path) =>
        !kiwi.find(path, true) && !arenaAugmentFallbacks[apiNameOf(path)]);
    if (needsLive && strings) {
        liveKiwi = indexBin(await settle(fetchJson(liveKiwiBinUrl)));
    }

    const report = { pbeBin: [], liveBin: [], fallback: [], metadataOnly: [], missing: [] };
    const arena = [];
    for (const path of cherryPaths) {
        const apiName = apiNameOf(path);
        let augment = null;
        const pbeEntry = kiwi.find(path, true);
        const liveEntry = !pbeEntry && liveKiwi ? liveKiwi.find(path, true) : undefined;
        if (pbeEntry) {
            augment = buildFromBin(pbeEntry, kiwi.bin, stringsOrEmpty, 'cherry', 'cdragon-kiwi');
            report.pbeBin.push(augment.name);
        } else if (liveEntry) {
            augment = buildFromBin(liveEntry, liveKiwi.bin, stringsOrEmpty, 'cherry', 'cdragon-kiwi-live');
            report.liveBin.push(augment.name);
        } else {
            augment = buildFromFallback(apiName, clientMetaByName[apiName.toLowerCase()], stringsOrEmpty);
            if (!augment) report.missing.push(apiName);
            else if (augment.dataSource === 'fallback') report.fallback.push(augment.name);
            else report.metadataOnly.push(augment.name);
        }
        // CHERRY membership is explicit, so this keeps entries kiwi.bin marks
        // `Enabled: false` (that flag is Mayhem's pool, not Arena's).
        if (augment) arena.push(augment);
    }

    let aram = null;
    if (kiwi.size > 0) {
        const kiwiPaths = modeList('KIWI')
            || Object.keys(kiwi.bin).filter((key) => kiwi.bin[key]?.__type === 'AugmentData');
        aram = kiwiPaths
            .map((path) => {
                const entry = kiwi.find(path, false);
                // Skip `Enabled: false` entries, matching CDTB's arenadata.py.
                if (entry) return entry.Enabled === false ? null : buildFromBin(entry, kiwi.bin, stringsOrEmpty, null, 'cdragon-kiwi');
                return buildFromFallback(apiNameOf(path), clientMetaByName[apiNameOf(path).toLowerCase()], stringsOrEmpty, false);
            })
            // Drops template entries with a blank display name (e.g. GoH_PentakillAug_Generic).
            .filter((augment) => augment && augment.name.trim());
    }

    console.log(
        `[modeAugments] Arena borrowed: ${report.pbeBin.length} from PBE kiwi.bin, ` +
        `${report.liveBin.length} from live kiwi.bin, ${report.fallback.length} from hard-coded fallbacks, ` +
        `${report.metadataOnly.length} metadata-only` +
        (report.missing.length ? `, missing: ${report.missing.join(', ')}` : '') +
        `. ARAM: ${aram ? aram.length : 'unavailable'}`
    );
    if (report.fallback.length) {
        console.log('[modeAugments] Using hard-coded fallback data for:', report.fallback.join(', '));
    }

    return { arena, aram, report };
}
